### PR TITLE
Add method to return all results

### PR DESCRIPTION
**Pull request by superdecimal**
@geoah what do you think?

### CODE REVIEW

**Comment by geoah** [comment]
Just replace the search method with the one you made, no reason to have both,  especially returning different types

**Comment by superdecimal** [comment]
I tried not to break functionality but ok :)

**Comment by geoah** [comment]
That's why we Glide, we should start tagging versions. Imo best to be
consistent then backwards compatible

**Comment by superdecimal** [comment]
Pun intended? :p Agree on both points.

**Comment by geoah** [comment]
Also, is there a reason you don't return by ref the torrents?

**Comment by superdecimal** [comment]
Not really. Should I switch?

**Comment by geoah** [comment]
Don't see a reason not to.

**Review by geoah — APPROVED** [review]
LGMT 👍

**Pull request merged**
